### ISSUE TITLE
Ensure Consistent Sheet Size

### ISSUE THREAD

**Issue by vedmakk** [vedmakk/doppelpunkt#5]
Always start with an A4 sized sheet (`min-height`, `width`) and ensure that it's approximately A4 across different screen densities (DPI) and screen scalings. Make sure to take the print padding into account (see `print.css`).

Show slight page-lines every XXXXpx to indicate page breaks.

You can approximate an A4-sized sheet using pixels, but to do it reliably, you need to take DPI (dots per inch) and screen scaling into account. Browsers render everything in CSS pixels, which aren’t the same as physical pixels due to high-DPI displays and user zoom settings.

We can approximate A4 size in the browser using pixels, and it will look correct at 96 DPI (default in CSS).

**📐 A4 Size in CSS Pixels (at 96 DPI)**

The real-world dimensions of A4 are:
- 210mm × 297mm
- That equals 8.27in × 11.69in

At 96 CSS pixels per inch:
- A4 width = 8.27 × 96 ≈ 794px
- A4 height = 11.69 × 96 ≈ 1123px

So, the A4-sized textarea (or container) can be:

width: 794px;
height: 1123px;

**💡 Practical Implementation**

Use a container div styled like a paper sheet:

```html
<div class="a4-sheet">
  <textarea></textarea>
</div>
```

```css
.a4-sheet {
  width: 794px;
  height: 1123px;
  padding: 40px;
  margin: auto;
  background: white;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
  box-sizing: border-box;
}
textarea {
  width: 100%;
  height: 100%;
  border: none;
  resize: none;
  outline: none;
  font: 16px serif;
}
```

**⚠️ Caveats**
1. Zoom and DPI scaling will affect how this appears physically on different screens.
2. It won’t match actual physical paper size unless printed with proper DPI settings (e.g. @media print rules).
3. Avoid using screen scaling tricks (like vw, vh, em for layout widths), as they won’t match printed output.

**🖨️ Accurate Print Output**

Use @page and @media print:

```
@media print {
  @page {
    size: A4;
    margin: 1in;
  }
  body {
    margin: 0;
  }
}
```

**🖨️ Testing for Print**

In dev tools:
- Use Print Preview in your browser.
- Or use Chrome’s DevTools → “Rendering” → “Emulate CSS Media type” → print.
